### ISSUE TITLE
ESJZone 關於備份工具的問題

### ISSUE THREAD

**Issue by oao0623** [ZALin/ESJZone-novel-mirror#4]
不好意思，最近看到幾部小說想存，想請問您這個備份工作要如何使用

**Comment by ZALin** [comment]
[備份工具](https://github.com/ZALin/ESJ-novel-backup) ：

Python 2.x 用 esjbackup.py
Python 3.x 用 esjbackup3.py

例如：
1. 從小說主頁備份
`python esjbackup.py https://www.esjzone.cc/detail/1599746513.html`

2. 從小說論壇備份
`python esjbackup.py https://www.esjzone.cc/forum/1584679807/1599746513/`

不過現在部份小說要登入才能看（尤其是日輕），在當下我還沒新增登入的功能。如果你可以自己修改，你也可以自己加 request header 的 Cookie (ews_key 和 ews_token)
